eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: springcloud-zipkin-server

server:
  port: 9411
zipkin:
  collector:
    rabbitmq:
      addresses: 101.89.191.244:5672
      password: abc
      username: abc
      queue: zipkin