server:
  #服务注册中心端口号
  port: 8761
spring:
  application:
    name: EurekaServer
eureka:
  instance:
    #服务注册中心实例的主机名,在hosts文件中添加
    hostname: peer1
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    service-url:
      #指定服务注册中心的位置,  两个eureka节点集群配置
      defaultZone: http://peer1:${server.port}/eureka/,http://peer2:8762/eureka/
  #关闭自我保护
#  server:
#    enableSelfPreservation: false