spring:
  application:
    name: api-gateway
server:
  port: 5555

# routes to serviceId 这里边是通过serviceid来绑定地址，当在路径后添加/api-a/   则是访问service-A对应的服务。
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
          path: /api-b/**
          serviceId: service-B

# routes to url  这里是绑定具体的ip地址
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2222/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/